# Задание1 

Использую свой подправленный код из первого домашнего задания: 


In [1]:
import numpy as np


In [16]:

index = {"A" : 1, "T": 2,  "G":3, "C":4 }

def n_w_matrix(seq1, seq2, matrix):
    matrix_weights = np.zeros((len(seq1)+1, len(seq2)+1))
 
    for i in range( 1,matrix_weights.shape[0]):
        for j in range(1 ,matrix_weights.shape[1]):
      
            s1 = matrix_weights[i-1,j-1]+matrix[index[seq1[i-1]],index[seq2[j-1]]]
            s2 = matrix_weights[i][j-1]+matrix[index[seq1[i-1]],0]
            s3 = matrix_weights[i-1][j]+matrix[0, index[seq2[j-1]]]
            matrix_weights[i][j] = max( 0,s1,s2,s3)
            
    #print(matrix_weights)
    maxi,maxj = np.unravel_index(matrix_weights.argmax(), matrix_weights.shape) # для старта с максимума 
    #print(i, j)
    max_score = np.amax(matrix_weights) 
    
    seq_alignment1 = ""
    seq_alignment2 = ""
    ind_i = len(seq1)
    jnd_j = len(seq2)
    i = maxi 
    j = maxj
    
        
    while(i>0 or j>0):
        if(matrix_weights[i][j]==0):
            break # завершаем при нуле 
 
        if (  (i>0 and j>0) and  matrix_weights[i][j] == matrix_weights[i-1][j-1]+ matrix[index[seq1[i-1]], index[seq2[j-1]]]):
            seq_alignment1  = seq1[i-1]+seq_alignment1 
            seq_alignment2  = seq2[j-1]+seq_alignment2 

            i-=1
            j-=1
    
        elif ( i>0 and matrix_weights[i][j] == matrix_weights[i-1][j]+ matrix[index[seq1[i-1]],0]):
        
            seq_alignment1  = seq1[i-1]+seq_alignment1 
            seq_alignment2  = "-"+seq_alignment2   
            i-=1
        else:
        
            seq_alignment1  = "-"+seq_alignment1 
            seq_alignment2  = seq2[j-1]+seq_alignment2         
            j=j-1
      # эта часть кода просто для удобного вывода выравнивания 
    if(i>=j):
        for e in range(i-1, -1, -1):
            seq_alignment1  = seq1[e].lower()+seq_alignment1      
        for e in range(j-1, -1, -1):
            seq_alignment2  = seq2[e].lower()+seq_alignment2    
        for e in range(0,i-j):
            seq_alignment2  = " "+seq_alignment2 
            
    else: 
        for e in range(j-1, -1, -1):
            seq_alignment2  = seq2[e].lower()+seq_alignment2    
        for e in range(i-1, -1, -1):
            seq_alignment1  = seq1[e].lower()+seq_alignment1    
        for e in range(0,j-i):
            seq_alignment1  = " "+seq_alignment1 
                
    for e in range(maxi+1, len(seq1)+1):
        seq_alignment1 = seq_alignment1 + seq1[e-1].lower()
    for e in range(maxj+1, len(seq2)+1):
        seq_alignment2 = seq_alignment2 + seq2[e-1].lower()    
    print(seq_alignment1)
    print(seq_alignment2)
    

    return seq_alignment1, seq_alignment2

Короткий пример: 

In [17]:
seq1 = "GATTACA"
seq2 = "GCATGCA"

matrix = np.array([[-1,-1,-1,-1,-1],[-1,1,-1,-1,-1],[-1,-1,1,-1,-1],[-1,-1,-1,1,-1],[-1,-1,-1,-1,1] ])
n_w_matrix(seq1, seq2, matrix)

 gATtaca
gcATgca


(' gATtaca', 'gcATgca')

Пример из прошлого домашнего задания, с той жа матрицей.
ДЗ1: https://github.com/kamilla0503/Bioinformatics_institute/blob/master/Algorithms/HW1_Task2.ipynb

In [18]:
seq1 = "GATTACAACCGTACACCTAGCCGAC"
seq2 = "GATTGCGATTACAACCGATTGATAC"

matrix = np.array([[-1,-2,-1,-1,-1],[-2,2,-2,-1,-1],[-1,-2,1,-1,-1],[-1,-1,-1,1,-1],[-1,-1,-1,-1,2] ])
n_w_matrix(seq1, seq2, matrix)

      GATTACAACCG--T-ACACctagccgac
gattgcGATTACAACCGATTGATAC


('      GATTACAACCG--T-ACACctagccgac', 'gattgcGATTACAACCGATTGATAC')

Результат глобального выравнивания: 

GATTACAACCGTAC-ACCTAGCCG--AC

GATTGCGAT--TACAACCGAT-TGATAC.

Видно, что при локальном выравнивании есть участок, на котором много совпадений. 
При глобальном выравнивании такого длинного участка совпадений нет. 


# Задание 2

In [34]:

index = {"A" : 1, "T": 2,  "G":3, "C":4 }

def s_w_matrix_gaps(seq1, seq2, matrix, afgap ):
    matrix_weights = np.zeros((len(seq1)+1, len(seq2)+1))
    
    sum_gaps = np.zeros((len(seq1)+1, len(seq2)+1))
 
    for i in range( 1,matrix_weights.shape[0]):
        for j in range(1 ,matrix_weights.shape[1]):
            
      
            s1 = matrix_weights[i-1,j-1]+matrix[index[seq1[i-1]],index[seq2[j-1]]]
            s2 = matrix_weights[i][j-1]+matrix[index[seq1[i-1]],0]+afgap*max(0, sum_gaps[i][j-1]-1)
            s3 = matrix_weights[i-1][j]+matrix[0, index[seq2[j-1]]]+afgap*max(0, sum_gaps[i-1][j]-1)
            matrix_weights[i][j] = max( 0,s1,s2,s3)
            if(matrix_weights[i][j] ==s2 ):
                sum_gaps[i][j] = sum_gaps[i][j-1]+1
            if(matrix_weights[i][j] ==s3 ):
                sum_gaps[i][j] = sum_gaps[i-1][j]+1
            
    print(matrix_weights)
    #print(sum_gaps)
    maxi,maxj = np.unravel_index(matrix_weights.argmax(), matrix_weights.shape) # для старта с максимума 
    #print(i, j)
    max_score = np.amax(matrix_weights) 
    
    seq_alignment1 = ""
    seq_alignment2 = ""
    ind_i = len(seq1)
    jnd_j = len(seq2)
    i = maxi 
    j = maxj
    
        
    while(i>0 or j>0):
        if(matrix_weights[i][j]==0):
            break # завершаем при нуле 
 
        if (  (i>0 and j>0) and  matrix_weights[i][j] == matrix_weights[i-1][j-1]+ matrix[index[seq1[i-1]], index[seq2[j-1]]]):
            seq_alignment1  = seq1[i-1]+seq_alignment1 
            seq_alignment2  = seq2[j-1]+seq_alignment2 

            i-=1
            j-=1
    
        elif ( i>0 and matrix_weights[i][j] == matrix_weights[i-1][j]+ matrix[index[seq1[i-1]],0]+afgap*max(0, sum_gaps[i-1][j]-1)):
        
            seq_alignment1  = seq1[i-1]+seq_alignment1 
            seq_alignment2  = "-"+seq_alignment2   
            i-=1
        else:
        
            seq_alignment1  = "-"+seq_alignment1 
            seq_alignment2  = seq2[j-1]+seq_alignment2         
            j=j-1
      # эта часть кода просто для удобного вывода выравнивания 
    if(i>=j):
        for e in range(i-1, -1, -1):
            seq_alignment1  = seq1[e].lower()+seq_alignment1      
        for e in range(j-1, -1, -1):
            seq_alignment2  = seq2[e].lower()+seq_alignment2    
        for e in range(0,i-j):
            seq_alignment2  = " "+seq_alignment2 
            
    else: 
        for e in range(j-1, -1, -1):
            seq_alignment2  = seq2[e].lower()+seq_alignment2    
        for e in range(i-1, -1, -1):
            seq_alignment1  = seq1[e].lower()+seq_alignment1    
        for e in range(0,j-i):
            seq_alignment1  = " "+seq_alignment1 
                
    for e in range(maxi+1, len(seq1)):
        seq_alignment1 = seq_alignment1 + seq1[e].lower()
    for e in range(maxj+1, len(seq2)):
        seq_alignment2 = seq_alignment2 + seq2[e].lower()    
    print(seq_alignment1)
    print(seq_alignment2)
    

    return seq_alignment1, seq_alignment2

пример из википедии: 

In [35]:
seq2 = "TGTTACGG"
seq1 = "GGTTGACTA"

matrix = np.array([[-2,-2,-2,-2,-2],[-2,3,-3,-3,-3],[-2,-3,3,-3,-3],[-2,-3,-3,3,-3],[-2,-3,-3,-3,3] ])
s_w_matrix_gaps(seq1, seq2, matrix, -2)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  6.]
 [ 0.  3.  1.  6.  4.  2.  0.  1.  4.]
 [ 0.  3.  1.  4.  9.  7.  5.  1.  2.]
 [ 0.  1.  6.  4.  7.  6.  4.  8.  6.]
 [ 0.  0.  4.  3.  5. 10.  8.  6.  5.]
 [ 0.  0.  2.  1.  1.  8. 13. 11.  9.]
 [ 0.  3.  1.  5.  4.  6. 11. 10.  8.]
 [ 0.  1.  0.  3.  2.  7.  9.  8.  7.]]
gGTTGACa
tGTT-ACg


('gGTTGACa', 'tGTT-ACg')

Тест 1

In [41]:
seq1="TCCCAGTTATGTCAGGGGACACGAGCATGCAGAGAC"
seq2="AATTGCCGCCGTCGTTTTCAGCAGTTATGTCAGATC"



matrix = np.zeros((5,5))
for i in range(1,5):
    for j in range(1,5):
        if(i==j):
            matrix[i][j]=1
        else:
            matrix[i][j]=-1
s_w_matrix_gaps(seq1, seq2, matrix, 0)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  1.  1.  1.]
 [ 0.  0.  0. ...  2.  2.  2.]
 ...
 [ 0.  1.  2. ... 22. 22. 22.]
 [ 0.  1.  2. ... 22. 22. 22.]
 [ 0.  1.  2. ... 22. 22. 23.]]
   T----CC--CAGTTATGTCAGGGGACACG--A-GCATGCAGA-GAC
aatTGCCGCCGTC-GTT-T-TCA---G-CA-GTTATG--T-CAGAT--C


('   T----CC--CAGTTATGTCAGGGGACACG--A-GCATGCAGA-GAC',
 'aatTGCCGCCGTC-GTT-T-TCA---G-CA-GTTATG--T-CAGAT--C')

Тест 2

In [42]:
matrix = np.zeros((5,5))
for i in range(0,5):
    for j in range(0,5):
        if(i==0 or j==0):
            matrix[i][j]=-100
        elif (i==j):
            matrix[i][j]=1
        else:
            matrix[i][j]=-1
s_w_matrix_gaps(seq1, seq2, matrix, -0.01)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 2.]
 ...
 [0. 0. 0. ... 0. 3. 0.]
 [0. 1. 1. ... 3. 0. 2.]
 [0. 0. 0. ... 0. 2. 1.]]
                  tccCAGTTATGTCAGggacacgagcatgcagagac
aattgccgccgtcgttttcagCAGTTATGTCAGtc


('                  tccCAGTTATGTCAGggacacgagcatgcagagac',
 'aattgccgccgtcgttttcagCAGTTATGTCAGtc')

Во втором тесте нет гэпов - они очень дорогие. 

Тест 3 

In [45]:
matrix = np.zeros((5,5))
for i in range(0,5):
    for j in range(0,5):
        if(i==0 or j==0):
            matrix[i][j]=0.5
        elif (i==j):
            matrix[i][j]=1
        else:
            matrix[i][j]=-1
s_w_matrix_gaps(seq1, seq2, matrix, -0.3)

[[ 0.   0.   0.  ...  0.   0.   0. ]
 [ 0.   0.5  1.  ...  1.   1.2  1.1]
 [ 0.   1.   1.2 ...  4.3  4.2  3.8]
 ...
 [ 0.   1.5  2.  ... 29.9 29.8 29.4]
 [ 0.   2.   2.5 ... 30.7 31.2 31.7]
 [ 0.   2.2  3.  ... 31.2 31.7 32.2]]
 T----C--C---CAGTTATGTCAGGGGACACG--A-GCATGCAGAGA-C
a-ATTGCCGCCGTC-GTT-T-TCAG----CA-GTTATG--T-C--AGATC


(' T----C--C---CAGTTATGTCAGGGGACACG--A-GCATGCAGAGA-C',
 'a-ATTGCCGCCGTC-GTT-T-TCAG----CA-GTTATG--T-C--AGATC')

В третьем тесте больше гэпов, чем в первом. Наверное, этому способствовало вознаграждение за открытие гэпа. 

# Задание 3 

In [46]:
import random 

In [50]:
nucls = ["A", "T", "G", "C"]

s_100 = ""
s_1000 = ""
s_100000 = ""

for i in range(100):
    s_100 = s_100 + random.choice(nucls)
    
    
for i in range(1000):
    s_1000 = s_1000 + random.choice(nucls)
    

for i in range(100000):
    s_100000 = s_100000 + random.choice(nucls)
    
print("100:")
print(s_100)
    
with open('seq100.txt', 'w') as the_file:
    the_file.write(s_100)
    
with open('seq1000.txt', 'w') as the_file:
    the_file.write(s_1000)
    
with open('seq10000.txt', 'w') as the_file:
    the_file.write(s_100000)

100:
GTACATGCGTCCGATGACAACGGACTTCATTTAAGACCACCGAGCAATCAGGACGGTTGTCTCTACTCCAATGTCCATGAGCCTATGGGTACCGCCCCCC


In [54]:

def gotoFunction(part, alf):
    goto = {}
    output = {}
    newstate = 0 
    for i in range(len(part)):
        state = 0
        j = 0
        while (state, part[i][j]) in goto.keys():
            state = goto[(state, part[i][j])]
            j += 1
        for p in range(j, len(part[i])):
            newstate = newstate+1 
            goto[(state, part[i][p])] = newstate
            state = newstate       
        output[state] = [part[i]]

    for a in alf:
        if (0, a) not in goto.keys():
            goto[(0, a)] = 0
            
    return goto, output

def failureFunction(part, symbols, goto, output): 
    failure = {}
    queue = []

    for a in symbols:
        if goto[(0, a)] != 0:
            s = goto[(0, a)]
            queue.append(s)
            failure[s] = 0 

    while queue != []:
        r = queue[0] 
        del queue[0] 

        for a in symbols:
            if (r, a) in goto.keys():
                s = goto[(r, a)]
                queue.append(s)
                state = failure[r] 

                while (state, a) not in goto.keys():
                    state = failure[state]


                failure[s] = goto[(state, a)]

                if failure[s] in output.keys():
                    output[s].extend(output[failure[s]])
                    
    return failure, output


def find(text, part):
    letters = set(list(''.join(part)))
    goto, output = gotoFunction(part, letters)
    failure, output = failureFunction(part, letters, goto, output)
    state = 0
    for i in range(len(text)):
        if text[i] in letters:
            while (state, text[i]) not in goto.keys() and state != 0:
                state = failure[state] 
            state = goto[(state, text[i])] 
            if state in output.keys():
                print(i+1, output[state])

In [55]:
find("GCAAAGC", "GC")

1 ['G']
2 ['C']
6 ['G']
7 ['C']
